spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB}
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    
  main:
    banner-mode: "off"
